server:
  address:     ":8000"
  serverRoot: "resource/public"

logger:
  path: "./logs/"
  file: "{Y-m-d}.log"
  stdout: true
  level: "info"
  rotateSize: "10M"
  rotateBackupLimit: 10
  rotateBackupExpire: "10d"
  rotateBackupCompress: 9
  rotateCheckInterval: "24h"

database:
  default:
    link: mysql:wromgs0xhe0qk1hkc4vt:pscale_pw_W7KVoXfCATiw4PnPRhA06q9pIQXT58XmySKN5HVq9kd@tcp(aws.connect.psdb.cloud:3306)/porkastdb?tls=true

redis:
  default:
    address: 47.243.182.236:6379
    db: 1
    pass: 1qaz!QAZ

celery:
  worker:
    count: 6

elastic:
  host: "http://47.243.182.236"
  port: "9200"
  username: "elastic"
  password: "qazxsw"
