server:
  address:     ":8000"
  serverRoot: "resource/public"

logger:
  path: "./logs/"
  file: "{Y-m-d}.log"
  stdout: true
  level: "info"
  rotateSize: "100M"
  rotateBackupLimit: 10
  rotateBackupExpire: "10d"
  rotateBackupCompress: 9
  rotateCheckInterval: "24h"

database:
  default:
    host: "rm-uf6zz7tf01t4n01ilio.rwlb.rds.aliyuncs.com"
    port: "3306"
    user: "guoshaofm"
    name: "guoshaofmdb"
    pass: "1qaz!QAZ"
    type: "mysql"
    weight: "100"
    createdAt: "true"
    updatedAt: "true"
    charset: "utf8"
    maxIdle: "10"
    maxOpen: "100"
    maxLifetime: "30s"

redis:
  default:
    address: 47.242.232.137:6379
    db: 1
    pass: 123456

