server:
  address:     ":8000"
  serverRoot: "resource/public"

logger:
  path: "./logs/"
  file: "{Y-m-d}.log"
  stdout: true
  level: "info"
  rotateSize: "10M"
  rotateBackupLimit: 10
  rotateBackupExpire: "10d"
  rotateBackupCompress: 9
  rotateCheckInterval: "24h"

database:
  default:
    host: "aws.connect.psdb.cloud"
    port: "3306"
    user: "wromgs0xhe0qk1hkc4vt"
    name: "porkastdb"
    pass: "pscale_pw_W7KVoXfCATiw4PnPRhA06q9pIQXT58XmySKN5HVq9kd"
    type: "mysql"
    weight: "100"
    createdAt: "true"
    updatedAt: "true"
    charset: "utf8"
    maxIdle: "10"
    maxOpen: "100"
    maxLifetime: "30s"

redis:
  default:
    address: 47.243.182.236:6379
    db: 1
    pass: 1qaz!QAZ

celery:
  worker:
    count: 6

elastic:
  host: "http://47.243.182.236"
  port: "9200"
  username: "elastic"
  password: "qazxsw"
