package consts


const FEED_CHANNEL_TOTAL_COUNT = "FEED_CHANNEL_TOTAL_COUNT"
const FEED_ITEM_TOTAL_COUNT = "FEED_ITEM_TOTAL_COUNT"
const TODAY_FEED_ITEM_LIST = "TODAY_FEED_ITEM_LIST"

const USER_SUB_KEYWORD_UPDATE = "user_sub_keyword_update"

const DAILY_FEED_ITEM_UPDATE_RECORD = "DAILY_FEED_ITEM_UPDATE_RECORD"
