// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"guoshao-fm-web/internal/model/entity"
	"guoshao-fm-web/internal/service/internal/dao/internal"
)

// feedChannelDao is the data access object for table feed_channel.
// You can define custom methods on it to extend its functionality as you wish.
type feedChannelDao struct {
	*internal.FeedChannelDao
}

var (
	// FeedChannel is globally public accessible object for table feed_channel operations.
	FeedChannel = feedChannelDao{
		internal.NewFeedChannelDao(),
	}
)

// Fill with you ideas below.

func GetFeedChannelInfoByChannelId(ctx context.Context, channelId string) (feedInfo entity.FeedChannel, err error) {

	err = FeedChannel.Ctx(ctx).Where("id=?", channelId).Scan(&feedInfo)

	return
}
