// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"porkast-server/internal/consts"
	"porkast-server/internal/model/entity"
	"porkast-server/internal/service/internal/dao/internal"

	"github.com/gogf/gf/v2/errors/gerror"
)

// keywordSubscriptionDao is the data access object for table keyword_subscription.
// You can define custom methods on it to extend its functionality as you wish.
type keywordSubscriptionDao struct {
	*internal.KeywordSubscriptionDao
}

var (
	// KeywordSubscription is globally public accessible object for table keyword_subscription operations.
	KeywordSubscription = keywordSubscriptionDao{
		internal.NewKeywordSubscriptionDao(),
	}
)

// Fill with you ideas below.
func CreateKeywordSubScriptionEntity(ctx context.Context, newEntity entity.KeywordSubscription) (err error) {
	var (
		queryEntity entity.UserSubKeyword
	)

	err = KeywordSubscription.Ctx(ctx).Where("keyword=? and country=? and exclude_feed_id=? and feed_item_id=?", newEntity.Keyword, newEntity.Country, newEntity.ExcludeFeedId, newEntity.FeedItemId).Scan(&queryEntity)

	if queryEntity.Id != "" {
		err = gerror.New(consts.DB_DATA_ALREADY_EXIST)
		return
	}

	_, err = KeywordSubscription.Ctx(ctx).Insert(newEntity)

	return
}
