// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"guoshao-fm-web/internal/service/internal/dao/internal"
)

// keywordSubscriptionDao is the data access object for table keyword_subscription.
// You can define custom methods on it to extend its functionality as you wish.
type keywordSubscriptionDao struct {
	*internal.KeywordSubscriptionDao
}

var (
	// KeywordSubscription is globally public accessible object for table keyword_subscription operations.
	KeywordSubscription = keywordSubscriptionDao{
		internal.NewKeywordSubscriptionDao(),
	}
)

// Fill with you ideas below.
