// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"porkast-server/internal/consts"
	"porkast-server/internal/dto"
	"porkast-server/internal/model/entity"
	"porkast-server/internal/service/internal/dao/internal"

	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/frame/g"
)

// keywordSubscriptionDao is the data access object for table keyword_subscription.
// You can define custom methods on it to extend its functionality as you wish.
type keywordSubscriptionDao struct {
	*internal.KeywordSubscriptionDao
}

var (
	// KeywordSubscription is globally public accessible object for table keyword_subscription operations.
	KeywordSubscription = keywordSubscriptionDao{
		internal.NewKeywordSubscriptionDao(),
	}
)

// Fill with you ideas below.
func CreateKeywordSubScriptionEntity(ctx context.Context, newEntity entity.KeywordSubscription) (err error) {
	var (
		queryEntity entity.UserSubKeyword
	)

	err = KeywordSubscription.Ctx(ctx).Where("keyword=? and country=? and exclude_feed_id=? and feed_item_id=?", newEntity.Keyword, newEntity.Country, newEntity.ExcludeFeedId, newEntity.FeedItemId).Scan(&queryEntity)

	if queryEntity.Id != "" {
		err = gerror.New(consts.DB_DATA_ALREADY_EXIST)
		return
	}

	_, err = KeywordSubscription.Ctx(ctx).Insert(newEntity)

	return
}

func GetKeywordSubscriptionCount(ctx context.Context, keyword, country, source, excludeFeedId string) (count int, err error) {
	
	count, err = KeywordSubscription.Ctx(ctx).Where("keyword=? and country=? and source=? and exclude_feed_id=?", keyword, country, source, excludeFeedId).Count()
	return
}

// get user sub keyword by user id and keyword
func GetSubKeywordItemsByUserIdAndKeyword(ctx context.Context, userId, keyword, source string, offset, limit int) (entities []dto.FeedItem, err error) {

	g.Model("feed_item fi").
		InnerJoin("keyword_subscription ks", "fi.id = ks.feed_item_id").
		InnerJoin("user_sub_keyword usk", "usk.keyword = ks.keyword and usk.country = ks.country and usk.exclude_feed_id = ks.exclude_feed_id and usk.source = ks.source").
		Fields("fi.*, ks.source, ks.exclude_feed_id, ks.country").
		Where("usk.user_id = ? and usk.keyword = ? and usk.source = ? and usk.status = 1", userId, keyword, source).
		Offset(offset).
		Limit(limit).
		OrderAsc("ks.id").
		Scan(&entities)

	return
}
