// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"porkast-server/internal/consts"
	"porkast-server/internal/dto"
	"porkast-server/internal/model/entity"
	"porkast-server/internal/service/internal/dao/internal"

	"github.com/gogf/gf/v2/errors/gcode"
	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/frame/g"
)

// userListenLaterDao is the data access object for table user_listen_later.
// You can define custom methods on it to extend its functionality as you wish.
type userListenLaterDao struct {
	*internal.UserListenLaterDao
}

var (
	// UserListenLater is globally public accessible object for table user_listen_later operations.
	UserListenLater = userListenLaterDao{
		internal.NewUserListenLaterDao(),
	}
)

// Fill with you ideas below.
func CreateListenLaterByUserIdAndFeedId(ctx context.Context, newEntity entity.UserListenLater) (err error) {
	var (
		queryEntity entity.UserListenLater
	)

	queryEntity, err = GetListenLaterByUserIdAndFeedId(ctx, newEntity.UserId, newEntity.ChannelId, newEntity.ItemId)
	if queryEntity.Id != "" {
		err = gerror.New(consts.DB_DATA_ALREADY_EXIST)
		return
	}

	if newEntity.UserId == "" || newEntity.ChannelId == "" || newEntity.ItemId == "" || newEntity.RegDate == nil || newEntity.RegDate.IsDST() {
		err = gerror.New(gcode.CodeMissingParameter.Message())
		return
	}

	_, err = UserListenLater.Ctx(ctx).Insert(newEntity)

	return
}

func GetListenLaterByUserIdAndFeedId(ctx context.Context, userId, channelId, itemId string) (entity entity.UserListenLater, err error) {

	if userId == "" || channelId == "" || itemId == "" {
		err = gerror.New(gcode.CodeMissingParameter.Message())
		return
	}
	err = UserListenLater.Ctx(ctx).Where("user_id=? and channel_id=? and item_id=? and status=1", userId, channelId, itemId).Scan(&entity)

	return
}

func GetListenLaterListByUserId(ctx context.Context, userId string, offset, limit int) (dtoList []dto.UserListenLater, err error) {

	if userId == "" {
		err = gerror.New(gcode.CodeMissingParameter.Message())
		return
	}

	g.Model("user_listen_later ull").
		InnerJoin("feed_item fi", "ull.item_id = fi.id").
		Fields("fi.*, ull.reg_date").
		Where("status=1 and user_id=?", userId).
		Offset(offset).
		Limit(limit).
		Order("ull.reg_date desc").
		Scan(&dtoList)

	return
}

func GetTotalListenLaterCountByUserId(ctx context.Context, userId string) (totalCount int, err error) {

	if userId == "" {
		err = gerror.New(gcode.CodeMissingParameter.Message())
		return
	}

	totalCount, err = UserListenLater.Ctx(ctx).Where("user_id=? and status=1", userId).Count()

	return
}
