// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"porkast-server/internal/model/entity"
	"porkast-server/internal/service/internal/dao/internal"
)

// userPlaylistDao is the data access object for table user_playlist.
// You can define custom methods on it to extend its functionality as you wish.
type userPlaylistDao struct {
	*internal.UserPlaylistDao
}

var (
	// UserPlaylist is globally public accessible object for table user_playlist operations.
	UserPlaylist = userPlaylistDao{
		internal.NewUserPlaylistDao(),
	}
)

// Fill with you ideas below.

func InsertNewUserPlaylist(ctx context.Context, newEntity entity.UserPlaylist) (err error) {
	_, err = UserPlaylist.Ctx(ctx).Insert(newEntity)
	return
}

func GetPlaylistById(ctx context.Context, id string) (entity entity.UserPlaylist, err error) {
	err = UserPlaylist.Ctx(ctx).Where("id=?", id).Scan(&entity)
	return
}