// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-11-09 00:40:46
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserSubscription is the golang structure of table user_subscription for DAO operations like Where/Data.
type UserSubscription struct {
	g.Meta        `orm:"table:user_subscription, do:true"`
	Id            interface{} //
	UserId        interface{} //
	CreateTime    *gtime.Time //
	Status        interface{} //
	Keyword       interface{} //
	OrderByDate   interface{} //
	Lang          interface{} // feed language
	Country       interface{} //
	ExcludeFeedId interface{} //
	Source        interface{} //
	RefId         interface{} // subscription type id, like listenlater, playlist id
	Type          interface{} // suscription type, like searchKeyword, playlist, listenlater
}
