// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-10-15 15:03:39
// =================================================================================

package entity

// FeedChannel is the golang structure for table feed_channel.
type FeedChannel struct {
	Id          string `json:"id"          ` //
	Title       string `json:"title"       ` //
	ChannelDesc string `json:"channelDesc" ` //
	ImageUrl    string `json:"imageUrl"    ` //
	Link        string `json:"link"        ` //
	FeedLink    string `json:"feedLink"    ` //
	Copyright   string `json:"copyright"   ` //
	Language    string `json:"language"    ` //
	Author      string `json:"author"      ` //
	OwnerName   string `json:"ownerName"   ` //
	OwnerEmail  string `json:"ownerEmail"  ` //
	FeedType    string `json:"feedType"    ` //
	Categories  string `json:"categories"  ` //
	Source      string `json:"source"      ` //
	FeedId      string `json:"feedId"      ` //
}
