// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-10-18 23:42:59
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// KeywordSubscription is the golang structure for table keyword_subscription.
type KeywordSubscription struct {
	Id            int         `json:"id"            ` //
	Keyword       string      `json:"keyword"       ` //
	FeedChannelId string      `json:"feedChannelId" ` //
	FeedItemId    string      `json:"feedItemId"    ` //
	CreateTime    *gtime.Time `json:"createTime"    ` //
	Country       string      `json:"country"       ` //
	Source        string      `json:"source"        ` //
	ExcludeFeedId string      `json:"excludeFeedId" ` //
}
