// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-11-02 00:17:47
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserPlaylistItem is the golang structure for table user_playlist_item.
type UserPlaylistItem struct {
	Id         string      `json:"id"         ` //
	PlaylistId string      `json:"playlistId" ` //
	ItemId     string      `json:"itemId"     ` //
	ChannelId  string      `json:"channelId"  ` //
	RegDate    *gtime.Time `json:"regDate"    ` //
	Status     int         `json:"status"     ` //
}
