// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-11-07 20:47:48
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserPlaylist is the golang structure for table user_playlist.
type UserPlaylist struct {
	Id             string      `json:"id"             ` //
	PlaylistName   string      `json:"playlistName"   ` //
	Description    []byte      `json:"description"    ` //
	UserId         string      `json:"userId"         ` //
	RegDate        *gtime.Time `json:"regDate"        ` //
	Status         int         `json:"status"         ` //
	CreatorId      string      `json:"creatorId"      ` // The playlist creator user id
	OrigPlaylistId string      `json:"origPlaylistId" ` // if the playlist is subscribed, this is the original user_playlist id
}
