// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-10-16 22:30:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserListenLater is the golang structure for table user_listen_later.
type UserListenLater struct {
	Id        string      `json:"id"        ` //
	UserId    string      `json:"userId"    ` //
	ItemId    string      `json:"itemId"    ` //
	ChannelId string      `json:"channelId" ` //
	RegDate   *gtime.Time `json:"regDate"   ` //
	Status    int         `json:"status"    ` //
}
