// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-11-09 00:40:46
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserSubscription is the golang structure for table user_subscription.
type UserSubscription struct {
	Id            string      `json:"id"            ` //
	UserId        string      `json:"userId"        ` //
	CreateTime    *gtime.Time `json:"createTime"    ` //
	Status        int         `json:"status"        ` //
	Keyword       string      `json:"keyword"       ` //
	OrderByDate   int         `json:"orderByDate"   ` //
	Lang          string      `json:"lang"          ` // feed language
	Country       string      `json:"country"       ` //
	ExcludeFeedId string      `json:"excludeFeedId" ` //
	Source        string      `json:"source"        ` //
	RefId         string      `json:"refId"         ` // subscription type id, like listenlater, playlist id
	Type          string      `json:"type"          ` // suscription type, like searchKeyword, playlist, listenlater
}
