// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-10-16 22:30:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// KeywordSubscriptionDao is the data access object for table keyword_subscription.
type KeywordSubscriptionDao struct {
	table   string                     // table is the underlying table name of the DAO.
	group   string                     // group is the database configuration group name of current DAO.
	columns KeywordSubscriptionColumns // columns contains all the column names of Table for convenient usage.
}

// KeywordSubscriptionColumns defines and stores column names for table keyword_subscription.
type KeywordSubscriptionColumns struct {
	Id            string //
	Keyword       string //
	FeedChannelId string //
	FeedItemId    string //
	CreateTime    string //
	Country       string //
	Source        string //
	ExcludeFeedId string //
}

//  keywordSubscriptionColumns holds the columns for table keyword_subscription.
var keywordSubscriptionColumns = KeywordSubscriptionColumns{
	Id:            "id",
	Keyword:       "keyword",
	FeedChannelId: "feed_channel_id",
	FeedItemId:    "feed_item_id",
	CreateTime:    "create_time",
	Country:       "country",
	Source:        "source",
	ExcludeFeedId: "exclude_feed_id",
}

// NewKeywordSubscriptionDao creates and returns a new DAO object for table data access.
func NewKeywordSubscriptionDao() *KeywordSubscriptionDao {
	return &KeywordSubscriptionDao{
		group:   "default",
		table:   "keyword_subscription",
		columns: keywordSubscriptionColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *KeywordSubscriptionDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *KeywordSubscriptionDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *KeywordSubscriptionDao) Columns() KeywordSubscriptionColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *KeywordSubscriptionDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *KeywordSubscriptionDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *KeywordSubscriptionDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
