// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-11-02 00:17:47
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserPlaylistItemDao is the data access object for table user_playlist_item.
type UserPlaylistItemDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns UserPlaylistItemColumns // columns contains all the column names of Table for convenient usage.
}

// UserPlaylistItemColumns defines and stores column names for table user_playlist_item.
type UserPlaylistItemColumns struct {
	Id         string //
	PlaylistId string //
	ItemId     string //
	ChannelId  string //
	RegDate    string //
	Status     string //
}

//  userPlaylistItemColumns holds the columns for table user_playlist_item.
var userPlaylistItemColumns = UserPlaylistItemColumns{
	Id:         "id",
	PlaylistId: "playlist_id",
	ItemId:     "item_id",
	ChannelId:  "channel_id",
	RegDate:    "reg_date",
	Status:     "status",
}

// NewUserPlaylistItemDao creates and returns a new DAO object for table data access.
func NewUserPlaylistItemDao() *UserPlaylistItemDao {
	return &UserPlaylistItemDao{
		group:   "default",
		table:   "user_playlist_item",
		columns: userPlaylistItemColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserPlaylistItemDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserPlaylistItemDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserPlaylistItemDao) Columns() UserPlaylistItemColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserPlaylistItemDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserPlaylistItemDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserPlaylistItemDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
